apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
  labels:
    name: redis
spec:
  replicas: 1
  selector:
    name: redis
  template:
   metadata:
    labels:
      name: redis
   spec:
    containers:
    - name: master
      image: kubeguide/redis-master
      ports:
      - containerPort: 6379